<a href="https://colab.research.google.com/github/MohammadAhmadSiddiqui/Capgemini-Training-/blob/main/GT_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

prices=np.array([100,200,300,400,500])
prices=prices*1.10
print(prices)
arr=np.array([[10,20,30],
              [40,50,60]])
arr=arr+5
print(arr)

[110. 220. 330. 440. 550.]
[[15 25 35]
 [45 55 65]]


In [ ]:
arr=np.array([10,20,30,40,50])
arr[1]


np.int64(20)

In [ ]:
arr[1:4]

array([20, 30, 40])

In [ ]:
sales_day1=np.array([120,85,60])
sales_day2=np.array([150,90,75])
total_sales=sales_day1+sales_day2
print(total_sales)
percentage_growth=((sales_day2-sales_day1)/sales_day1)*100
print(percentage_growth)
highest_growth=np.argmax(percentage_growth)
if highest_growth==0:
    print("Highest Growth=A")
elif highest_growth==1:
    print("Highest Growth=B")
else:
    print("Highest Growth=C")



[270 175 135]
[25.          5.88235294 25.        ]
Highest Growth=A


In [ ]:
temps=np.array([[25,28,30],
                [22,24,26],
                [30,32,33],
                [27,29,31],
                [20,21,23]])
temps2=(temps*(9/5))+32
print(temps2)
correction=np.array([1,-1,0])
adjusted=temps+correction
print(adjusted)

[[77.  82.4 86. ]
 [71.6 75.2 78.8]
 [86.  89.6 91.4]
 [80.6 84.2 87.8]
 [68.  69.8 73.4]]
[[26 27 30]
 [23 23 26]
 [31 31 33]
 [28 28 31]
 [21 20 23]]


In [ ]:
bp=np.array([[120,80],
             [135,85],
             [140,90],
             [110,70],
             [125,75]])
systolic=bp[:,0]
print(systolic)
high_bp=bp[bp[:,0]>130]
print("High BP:")
print(high_bp)
print("Replaced values:")
bp[bp[:,1]<80,1]=80
print(bp)


[120 135 140 110 125]
High BP:
[[135  85]
 [140  90]]
Replaced values:
[[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]


In [ ]:
yields=np.array([[2.5,3.0,1.0],
                 [2.8,3.2,2.0],
                 [3.1,2.9,2.2],
                 [2.6,3.1,1.9]])
yields[1]=yields[1]+np.array([0.2,0.3,0.1])
print("Value added to second region")
print(yields)
yields[:,2]=yields[:,2]*1.1
print("Multiply Coulmn C by 1.1")
print(yields)
avg=np.mean(yields,axis=0)
print("highest Average yield:",np.argmax(avg))


Value added to second region
[[2.5 3.  1. ]
 [3.  3.5 2.1]
 [3.1 2.9 2.2]
 [2.6 3.1 1.9]]
Multiply Coulmn C by 1.1
[[2.5  3.   1.1 ]
 [3.   3.5  2.31]
 [3.1  2.9  2.42]
 [2.6  3.1  2.09]]
highest Average yield: 1


In [ ]:
scores=np.array([[85,78,92],
         [88,74,90],
         [70,65,80],
         [95,89,96]
         ])
top_two=scores[:2]
print("Top Two Students:")
print(top_two)
math=scores[:,0]
print("Maths Scores:",math)
science=scores[scores[:,2]>90]
print("High Scores in science:",science)

Top Two Students:
[[85 78 92]
 [88 74 90]]
Maths Scores: [85 88 70 95]
High Scores in science: [[85 78 92]
 [95 89 96]]


In [ ]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])
matrix[0]
matrix[:,1]
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
crops=np.array([[9000,5600,780,890],
               [7800,6500,468,7674],
               [560,877,655,2500],
               ])
crops=crops*1.10
print("Yield increased by 10%:",crops)
print("Wheat's yield:", crops[0])
print("Average yield per crop accross all seasons:",np.mean(crops,axis=1))
print("Yields greater than 3000:",crops[crops>3000])


Yield increased by 10%: [[9900.  6160.   858.   979. ]
 [8580.  7150.   514.8 8441.4]
 [ 616.   964.7  720.5 2750. ]]
Wheat's yield: [9900. 6160.  858.  979.]
Average yield per crop accross all seasons: [4474.25 6171.55 1262.8 ]
Yields greater than 3000: [9900.  6160.  8580.  7150.  8441.4]


In [ ]:
import numpy as np

# Create 2D array
production = np.array([
    [450, 520, 480, 500],   # Gadgets
    [300, 350, 400, 380],   # Tools
    [600, 650, 700, 720]    # Machines
])

print("Original Production Data:\n", production)
production_updated = production * 1.05
print("After 5% Increase:\n", production_updated)
gadgets = production_updated[0]
print("Gadgets Production:", gadgets)
average_production = np.mean(production_updated, axis=1)
print("Average Production per Product:", average_production)
high_production = production_updated[production_updated > 500]
print("Production values greater than 500:\n", high_production)

Original Production Data:
 [[450 520 480 500]
 [300 350 400 380]
 [600 650 700 720]]
After 5% Increase:
 [[472.5 546.  504.  525. ]
 [315.  367.5 420.  399. ]
 [630.  682.5 735.  756. ]]
Gadgets Production: [472.5 546.  504.  525. ]
Average Production per Product: [511.875 375.375 700.875]
Production values greater than 500:
 [546.  504.  525.  630.  682.5 735.  756. ]


In [ ]:
import pandas as pd

data = {
    "Name":["A","B","C"],
    "Salary":[50000,60000,55000]
}
df=pd.DataFrame(data)
print(df)

  Name  Salary
0    A   50000
1    B   60000
2    C   55000


In [ ]:
type(df["Salary"])

pandas.core.series.Series

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving sample_data1.csv to sample_data1 (1).csv


In [ ]:
import pandas as pd
df=pd.read_csv("sample_data1.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Employee_ID         15 non-null     int64  
 1   Department          15 non-null     object 
 2   Region              15 non-null     object 
 3   Salary              15 non-null     int64  
 4   Experience_Years    15 non-null     int64  
 5   Performance_Rating  14 non-null     float64
 6   Monthly_Sales       14 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 972.0+ bytes


Employee_ID        Salary  Experience_Years  Performance_Rating  \
count    15.000000     15.000000         15.000000           14.000000   
mean   1008.000000  49666.666667          3.200000            3.785714   
std       4.472136   7158.079019          1.373213            0.892582   
min    1001.000000  39000.000000          1.000000            2.000000   
25%    1004.500000  45500.000000          2.000000            3.000000   
50%    1008.000000  49000.000000          3.000000            4.000000   
75%    1011.500000  52500.000000          4.000000            4.000000   
max    1015.000000  62000.000000          6.000000            5.000000   

       Monthly_Sales  
count      14.000000  
mean    76928.571429  
std     62039.025293  
min         0.000000  
25%         0.000000  
50%     95000.000000  
75%    128750.000000  
max    150000.000000

In [ ]:
df[df["Region"]=="North"]

Employee_ID Department Region  Salary  Experience_Years  \
0          1001      Sales  North   45000                 2   
4          1005         IT  North   60000                 5   
8          1009      Sales  North   46000                 3   
12         1013         IT  North   61000                 5   

    Performance_Rating  Monthly_Sales  
0                  4.0       120000.0  
4                  4.0            0.0  
8                  4.0       125000.0  
12                 4.0            NaN

In [ ]:
df.sort_values("Monthly_Sales",ascending=False)

Employee_ID Department Region  Salary  Experience_Years  \
2          1003      Sales   East   47000                 4   
10         1011      Sales   East   50000                 4   
13         1014      Sales  South   49000                 3   
5          1006      Sales  South   48000                 3   
8          1009      Sales  North   46000                 3   
0          1001      Sales  North   45000                 2   
1          1002  Marketing  South   52000                 3   
11         1012  Marketing   West   53000                 3   
6          1007  Marketing   East   51000                 2   
3          1004         HR   West   40000                 1   
4          1005         IT  North   60000                 5   
7          1008         IT   West   62000                 6   
9          1010         HR  South   39000                 2   
14         1015         HR   East   42000                 2   
12         1013         IT  North   61000                 5   

    Performance_Rating  Monthly_Sales  
2                  5.0       150000.0  
10                 5.0       140000.0  
13                 4.0       135000.0  
5                  4.0       130000.0  
8                  4.0       125000.0  
0                  4.0       120000.0  
1                  3.0        98000.0  
11                 NaN        92000.0  
6                  2.0        87000.0  
3                  3.0            0.0  
4                  4.0            0.0  
7                  5.0            0.0  
9                  3.0            0.0  
14                 3.0            0.0  
12                 4.0            NaN

In [ ]:
df.groupby("Region")["Monthly_Sales"].sum()

Region
East     377000.0
North    245000.0
South    363000.0
West      92000.0
Name: Monthly_Sales, dtype: float64

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Dataset  - Sheet1.csv to Dataset  - Sheet1.csv


In [ ]:
import pandas as pd

df = pd.read_csv("Dataset  - Sheet1.csv")

df.head()

Employee Department Quarter  Score
0     Amit      Sales      Q1     78
1    Priya         HR      Q1     85
2     John         IT      Q1     92
3     Sara    Finance      Q1     88
4    David      Sales      Q2     95

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Employee    10 non-null     object
 1   Department  10 non-null     object
 2   Quarter     10 non-null     object
 3   Score       10 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes


In [ ]:
df.describe()

Score
count  10.000000
mean   85.300000
std     9.177872
min    70.000000
25%    78.500000
50%    86.500000
75%    91.500000
max    99.000000

In [ ]:
top_performers = df[df["Score"] > 90]
print(top_performers)
sales_data = df[df["Department"] == "Sales"]
print(sales_data)
df_sorted = df.sort_values(by="Score", ascending=False)
print(df_sorted)
df_dept_sorted = df.sort_values(by=["Department", "Score"], ascending=[True, False])
print(df_dept_sorted)
avg_dept_score = df.groupby("Department")["Score"].mean()
print(avg_dept_score)
max_quarter_score = df.groupby("Quarter")["Score"].max()
print(max_quarter_score)
#avg_dept_score.plot(kind="bar", title="Average Score per Department")

  Employee Department Quarter  Score
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99
  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99
  Employee Department Quarter  Score
8     Neha      Sales      Q3     99
4    David      Sales      Q2     95
2     John         IT      Q1     92
7     Ravi    Finance      Q2     90
3     Sara    Finance      Q1     88
1    Priya         HR      Q1     85
5    Meera         HR      Q2     80
0     Amit      Sales      Q1     78
9    Karan         IT      Q3     76
6     Alex         IT      Q2     70
  Employee Department Quarter  Score
7     Ravi    Finance      Q2     90
3     Sara    Finance      Q1     88
1    Priya         HR      Q1     85
5    Meera         HR      Q2     80
2     John         IT      Q1     92
9    Karan         IT      Q3     76
6     Alex         IT      Q2     70
8

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Sales.csv to Sales.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Customers.csv to Customers.csv


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving support.csv to support.csv


In [ ]:
import pandas as pd

customers = pd.read_csv("Customers.csv")
sales = pd.read_csv("Sales.csv")
support = pd.read_csv("support.csv")



In [ ]:
print("Customers Info:")
print(customers.info())
print("Sales Info:")
print(sales.info())
print("Support Info:")
print(support.info())


Customers Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CustomerID  8 non-null      object 
 1   Name        8 non-null      object 
 2   Age         7 non-null      float64
 3   Region      8 non-null      object 
 4   SignupDate  8 non-null      object 
dtypes: float64(1), object(4)
memory usage: 452.0+ bytes
None
Sales Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   OrderID     8 non-null      object
 1   CustomerID  8 non-null      object
 2   Product     8 non-null      object
 3   Quantity    8 non-null      int64 
 4   Price       8 non-null      int64 
 5   OrderDate   8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes
None
Support Info:
<class 'pandas.core.frame.Dat

In [ ]:
customers["Age"].fillna(customers["Age"].median(), inplace=True)


/tmp/ipython-input-901496689.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers["Age"].fillna(customers["Age"].median(), inplace=True)


In [ ]:
print(customers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   CustomerID  8 non-null      object 
 1   Name        8 non-null      object 
 2   Age         8 non-null      float64
 3   Region      8 non-null      object 
 4   SignupDate  8 non-null      object 
dtypes: float64(1), object(4)
memory usage: 452.0+ bytes
None


In [ ]:
customers.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
sales.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
support.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)



In [ ]:
sales["DiscountedPrice"]=sales["Price"]*0.9
sales["Revenue"]=sales["Quantity"]*sales["Price"]

In [ ]:
may_orders = sales[sales["OrderDate"].str.startswith("2023-05")]
print("May Orders:\n",may_orders)
print("First 10 Sales Records:\n", sales.head(10))


May Orders:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0   
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0   

   Revenue  
2    45000  
3    60000  
First 10 Sales Records:
   OrderID Cust_ID     Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001      Laptop         2  55000  2023-04-10          49500.0   
1   O1002    C002      Mobile         1  25000  2023-04-12          22500.0   
2   O1003    C003      Tablet         3  15000  2023-05-01          13500.0   
3   O1004    C004      Laptop         1  60000  2023-05-15          54000.0   
4   O1005    C005      Mobile         2  22000  2023-06-05          19800.0   
5   O1006    C006  Headphones         5   2000  2023-06-10           1800.0   
6   O1007    C007      Laptop         1  58000  2023-07-02          52200.0   
7   O1008    C008      Tablet         2  18000  2023-07-20       

In [ ]:
north_customers = customers[customers["Region"] == "North"]
high_value_orders = sales[sales["Revenue"] > 10000]

print("\nNorth Customers:\n", north_customers)
print("\nHigh Value Orders:\n", high_value_orders)



North Customers:
   Cust_ID   Name   Age Region  SignupDate
0    C001   Amit  28.0  North  2023-01-15
4    C005  David  30.0  North  2023-02-10

High Value Orders:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0   
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0   
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0   
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0   
4   O1005    C005  Mobile         2  22000  2023-06-05          19800.0   
6   O1007    C007  Laptop         1  58000  2023-07-02          52200.0   
7   O1008    C008  Tablet         2  18000  2023-07-20          16200.0   

   Revenue  
0   110000  
1    25000  
2    45000  
3    60000  
4    44000  
6    58000  
7    36000  


In [ ]:
#Grouping
avg_revenue=sales.groupby("Product")["Revenue"].mean()
print(avg_revenue)
avg_resolution_issue=support.groupby("IssueType")["ResolutionTime"].mean()
print(avg_resolution_issue)

Product
Headphones    10000.0
Laptop        76000.0
Mobile        34500.0
Tablet        40500.0
Name: Revenue, dtype: float64
IssueType
Delivery Delay    38.000000
Payment Issue     18.666667
Product Defect    66.000000
Name: ResolutionTime, dtype: float64


In [ ]:
#merge cutomers,sales,support datasets on customer_id
merged_data = sales.merge(customers, on="Cust_ID").merge(support, on="Cust_ID")
print("Merged Dataset:\n", merged_data.head())

Merged Dataset:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0   
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0   
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0   
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0   
4   O1005    C005  Mobile         2  22000  2023-06-05          19800.0   

   Revenue   Name   Age Region  SignupDate TicketID       IssueType  \
0   110000   Amit  28.0  North  2023-01-15     T001  Delivery Delay   
1    25000  Priya  35.0  South  2022-11-20     T002   Payment Issue   
2    45000   John  33.0   East  2023-03-05     T003  Product Defect   
3    60000   Sara  42.0   West  2021-07-12     T004  Delivery Delay   
4    44000  David  30.0  North  2023-02-10     T005   Payment Issue   

   ResolutionTime  
0              48  
1              24  
2              72  
3              36  
4    

In [ ]:
#Create new calculated fields:
#	Customer Lifetime Value (CLV) = total revenue per customer.
#	Average Resolution Time per Customer
clv = sales.groupby("Cust_ID")["Revenue"].sum().reset_index()
clv.rename(columns={"Revenue": "CustomerLifetimeValue"}, inplace=True)
customers = customers.merge(clv, on="Cust_ID", how="left")
print("Customers with CLV:\n", customers)
avg_resolution_time = support.groupby("Cust_ID")["ResolutionTime"].mean().reset_index()
avg_resolution_time.rename(columns={"ResolutionTime": "AverageResolutionTime"}, inplace=True)
customers = customers.merge(avg_resolution_time, on="Cust_ID", how="left")
print("Customers with Average Resolution Time:\n", customers)


Customers with CLV:
   Cust_ID   Name   Age Region  SignupDate  CustomerLifetimeValue_x  \
0    C001   Amit  28.0  North  2023-01-15                   110000   
1    C002  Priya  35.0  South  2022-11-20                    25000   
2    C003   John  33.0   East  2023-03-05                    45000   
3    C004   Sara  42.0   West  2021-07-12                    60000   
4    C005  David  30.0  North  2023-02-10                    44000   
5    C006  Meera  27.0  South  2022-09-18                    10000   
6    C007   Alex  33.0   East  2023-01-25                    58000   
7    C008   Ravi  40.0   West  2022-12-01                    36000   

   AverageResolutionTime  CustomerLifetimeValue_y  
0                   48.0                   110000  
1                   24.0                    25000  
2                   72.0                    45000  
3                   36.0                    60000  
4                   12.0                    44000  
5                   60.0            

In [ ]:

customers = customers.merge(clv, on="Cust_ID", how="left")
print("Customers with CLV:\n", customers)



Customers with CLV:
   Cust_ID   Name   Age Region  SignupDate  CustomerLifetimeValue_x  \
0    C001   Amit  28.0  North  2023-01-15                   110000   
1    C002  Priya  35.0  South  2022-11-20                    25000   
2    C003   John  33.0   East  2023-03-05                    45000   
3    C004   Sara  42.0   West  2021-07-12                    60000   
4    C005  David  30.0  North  2023-02-10                    44000   
5    C006  Meera  27.0  South  2022-09-18                    10000   
6    C007   Alex  33.0   East  2023-01-25                    58000   
7    C008   Ravi  40.0   West  2022-12-01                    36000   

   AverageResolutionTime_x  CustomerLifetimeValue_y  AverageResolutionTime_y  \
0                     48.0                   110000                     48.0   
1                     24.0                    25000                     24.0   
2                     72.0                    45000                     72.0   
3                     36.0 

In [ ]:
#export cleaned dataset
merged_data.to_csv("Cleaned_Data.csv", index=False)
print("Cleaned dataset exported to Cleaned_Data.csv")



Cleaned dataset exported to Cleaned_Data.csv
